# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CfSchedulesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Cf schedules'
  		@cf_schedules = CfSchedule.order(sort_order(:desktop)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View cf schedule'
      @cf_schedule = CfSchedule.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new cf schedule'
    	@cf_schedule = CfSchedule.new
    end

    def create
      @cf_schedule = CfSchedule.new cf_schedule_params
    
      if @cf_schedule.save
        flash[:notice] = 'Cf schedule created'
        redirect_to casein_cf_schedules_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new cf schedule'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update cf schedule'
      
      @cf_schedule = CfSchedule.find params[:id]
    
      if @cf_schedule.update_attributes cf_schedule_params
        flash[:notice] = 'Cf schedule has been updated'
        redirect_to casein_cf_schedules_path
      else
        flash.now[:warning] = 'There were problems when trying to update this cf schedule'
        render :action => :show
      end
    end
 
    def destroy
      @cf_schedule = CfSchedule.find params[:id]

      @cf_schedule.destroy
      flash[:notice] = 'Cf schedule has been deleted'
      redirect_to casein_cf_schedules_path
    end
  
    private
      
      def cf_schedule_params
        params.require(:cf_schedule).permit(:desktop, :mobile)
      end

  end
end