# Scaffolding generated by Casein v5.1.1.5

module Casein
  class GroupclassesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Groupclasses'
  		@groupclasses = Groupclass.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View groupclass'
      @groupclass = Groupclass.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new groupclass'
    	@groupclass = Groupclass.new
    end

    def create
      @groupclass = Groupclass.new groupclass_params
    
      if @groupclass.save
        flash[:notice] = 'Groupclass created'
        redirect_to casein_groupclasses_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new groupclass'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update groupclass'
      
      @groupclass = Groupclass.find params[:id]
    
      if @groupclass.update_attributes groupclass_params
        flash[:notice] = 'Groupclass has been updated'
        redirect_to casein_groupclasses_path
      else
        flash.now[:warning] = 'There were problems when trying to update this groupclass'
        render :action => :show
      end
    end
 
    def destroy
      @groupclass = Groupclass.find params[:id]

      @groupclass.destroy
      flash[:notice] = 'Groupclass has been deleted'
      redirect_to casein_groupclasses_path
    end
  
    private
      
      def groupclass_params
        params.require(:groupclass).permit(:title, :length, :description)
      end

  end
end