# Scaffolding generated by Casein v5.1.1.5

module Casein
  class WorkoutsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Workouts'
  		@workouts = Workout.page(params[:page]).order('created_at DESC')
      # order(:date).paginate(:page => params[:page], :per_page => 6)
    end
  
    def show
      @casein_page_title = 'View workout'
      @workout = Workout.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new workout'
    	@workout = Workout.new
    end

    def create
      @workout = Workout.new workout_params
    
      if @workout.save
        flash[:notice] = 'Workout created'
        redirect_to casein_workouts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new workout'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update workout'
      
      @workout = Workout.find params[:id]
    
      if @workout.update_attributes workout_params
        flash[:notice] = 'Workout has been updated'
        redirect_to casein_workouts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this workout'
        render :action => :show
      end
    end
 
    def destroy
      @workout = Workout.find params[:id]

      @workout.destroy
      flash[:notice] = 'Workout has been deleted'
      redirect_to casein_workouts_path
    end
  
    private
      
      def workout_params
        params.require(:workout).permit(:date, :info, :strength, :conditioning)
      end

  end
end