development:
  adapter: postgresql
  database: cfi_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cfi_development
  pool: 5

production:
  adapter: postgresql
  database: cfi_development
  pool: 5