# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d08491ad26482e6e431790f6b0d92fedbd29b7fba9a3fb9c87f7802982d14bf3e9ff81ac671c6296c1be087dfac3e3b5339f76d1d32e3748c0dbb6c8a41a45f0

test:
  secret_key_base: d96dd6943850c29a40e934b32f1936e648ff788f12d308df47dc32ddc13c75d3b1354e6d6f433e5916d9a1c458ae6843dbb641a71031e7988dde1f165a333d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
